spring.application.name: post-service

server.port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${POST_SERVICE_DB_HOST}:${POST_SERVICE_DB_PORT}/${POST_SERVICE_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    config:
      import-check:
        enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_NAME}:${DISCOVERY_SERVICE_PORT}/eureka/
    healthcheck:
      enabled: true
