spring.application.name: POST-SERVICE

server.port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/post_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    config:
      import-check:
        enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
