server.port: 8082
eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka/
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/post_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create

user.service.url: http://user-service:8081
